services:
  php:
    build:
      context: .
      dockerfile: ./docker/ci/Dockerfile
    container_name: deperlas
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - shared
  
  webserver:
    image: nginx:alpine
    container_name: deperlas_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/ci/server/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared
    depends_on:
      - php

networks:
  shared:
    external: true