services:
  php:
    build:
      context: .
      dockerfile: ./docker/ci/Dockerfile.prod
    image: deperlas
    container_name: deperlas
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
    working_dir: /var/www/html
    networks:
      - shared

  
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - php
    networks:
      - shared
  
  node:
    build:
      context: .
      dockerfile: ./docker/ci/Dockerfile.vite
    container_name: node
    volumes:
      - .:/var/www/html
    networks:
      - shared

networks:
  shared:
    external: true