services:
  php:
    build:
      context: .
      dockerfile: ./docker/ci/Dockerfile.prod
    image: deperlas
    container_name: deperlas
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
    working_dir: /var/www/html
    networks:
      - shared

  
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - php
    networks:
      - shared
  
  node:
    image: node:22-alpine
    container_name: node_smt4
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - 5173:5173
    networks:
      - shared

networks:
  shared:
    external: true