name: Deploy ke EC2 Server

on:
  push:
    branches: [ dev ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      # - name: Decode SSH Key
      #   run: |
      #     echo "${{ secrets.EC2_KEY }}" | base64 -d > private_key.pem
      #     chmod 600 private_key.pem
      
      - name: Deploy ke EC2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/project_semester4
            git pull origin dev
            docker compose -f docker-compose.prod.yml up -d --build
