name: Deploy Laravel ke VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy ke VPS
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.EC2_USER }}
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_KEY}}
          script: |
            cd /var/www/deperlas
            git pull origin main
            npm run ci 
            npm run build
            php artisan optimize:clear
            php artisan optimize 
            sudo systemctl restart php8.4-fpm
            sudo systemctl restart nginx
        